import "../css/fonts.css"
import "../css/globals.css"
import "../css/address.css"
import "../css/404.css"
import "../css/benefits.css"
import "../css/breadcrumbs.css"
import "../css/burger.css"
import "../css/burgerMenu.css"
import "../css/contactMap.css"
import "../css/drayers.css"
import "../css/efficient.css"
import "../css/efficient2.css"
import "../css/generalHero.css"
import "../css/homePriceBanner.css"
import "../css/imageBanner.css"
import "../css/imageWithText.css"
import "../css/map.css"
import "../css/pickupProcess.css"
import "../css/textBanner.css"
import "../css/washProcess.css"
import "../css/washFold.css"
import "../css/pickupDeliveryScreen.css"
export default function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}